### ISSUE TITLE
反馈bug（级别：灾难）：仁慈的虚空不生效

### ISSUE THREAD

**Issue by sparrowprime** [hhhfsj/Pigeon-Server-issues#2]
虚空中会受到伤害死亡，所有的东西都锁到y=0那一层的墓碑里了，墓碑的钥匙锁在了第二个墓碑里，无法继续进行正常游戏。
![DSF0AUSPJ4GQ3}6Z@54O6LO](https://user-images.githubusercontent.com/87871590/154804304-5542b0b9-10ec-434f-be2c-e71609a39b1b.png)

**Comment by skyfsj** [comment]
想办法下去按shift就可以拿起了

sparrowprime ***@***.***>于2022年2月19日 周六22:10写道：

**Comment by skyfsj** [comment]
那个仁慈的虚空貌似被海绵吞了

fsj ***@***.***>于2022年2月19日 周六22:11写道：

**Comment by sparrowprime** [comment]
> 

说的好，我也是这么想的，你猜第二个墓碑是怎么来的

**Comment by skyfsj** [comment]
麻烦给下死亡坐标和玩家id

sparrowprime ***@***.***>于2022年2月19日 周六22:14写道：
